spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/spring_security6
    username: postgres
    password: password770
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
